# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-03 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmap',
            name='fmeColumnType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FMEDataTypes', to='api.FMEDataTypes'),
        ),
    ]
