# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 19:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_auto_20180910_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformers',
            fields=[
                ('transformer_id', models.AutoField(primary_key=True, serialize=False)),
                ('transformer_type', models.CharField(max_length=64)),
                ('ts1_name', models.CharField(max_length=64)),
                ('ts1_value', models.CharField(max_length=64)),
                ('ts2_name', models.CharField(max_length=64)),
                ('ts2_value', models.CharField(max_length=64)),
                ('ts3_name', models.CharField(max_length=64)),
                ('ts3_value', models.CharField(max_length=64)),
                ('ts4_name', models.CharField(max_length=64)),
                ('ts4_value', models.CharField(max_length=64)),
                ('ts5_name', models.CharField(max_length=64)),
                ('ts5_value', models.CharField(max_length=64)),
                ('ts6_name', models.CharField(max_length=64)),
                ('ts6_value', models.CharField(max_length=64)),
                ('whenCreated', models.DateTimeField(auto_now_add=True)),
                ('whenUpdated', models.DateTimeField(auto_now=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trans_jobs', to='api.ReplicationJobs')),
                ('whoCreated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_user_created', to=settings.AUTH_USER_MODEL)),
                ('whoUpdated', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trans_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
