# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-23 20:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('dest_key', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('dest_service_name', models.CharField(max_length=30)),
                ('dest_host', models.CharField(max_length=30)),
                ('dest_port', models.IntegerField(blank=True, null=True)),
                ('dest_type', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='FieldMap',
            fields=[
                ('fieldMapId', models.AutoField(primary_key=True, serialize=False)),
                ('sourceColumnName', models.CharField(max_length=64)),
                ('destColumnName', models.CharField(max_length=64)),
                ('whenCreated', models.DateTimeField(auto_now_add=True)),
                ('whenUpdated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FMEDataTypes',
            fields=[
                ('fieldTypeId', models.AutoField(primary_key=True, serialize=False)),
                ('fieldType', models.CharField(max_length=30)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='JobStatistics',
            fields=[
                ('jobStatsId', models.AutoField(primary_key=True, serialize=False)),
                ('jobStatus', models.CharField(max_length=25)),
                ('fmeServerJobId', models.IntegerField(null=True)),
                ('jobStarted', models.DateTimeField()),
                ('jobCompleted', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ReplicationJobs',
            fields=[
                ('jobid', models.AutoField(primary_key=True, serialize=False)),
                ('jobStatus', models.CharField(max_length=20)),
                ('cronStr', models.CharField(max_length=25)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('destEnvKey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destEnvKey', to='api.Destinations')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('sourceid', models.AutoField(primary_key=True, serialize=False)),
                ('sourceTable', models.CharField(help_text='Source Table Name', max_length=30)),
                ('sourceType', models.CharField(choices=[('FGDB', 'File Geodatabase')], default='FGDB', max_length=30)),
                ('sourceDBSchema', models.CharField(blank=True, max_length=30, null=True)),
                ('sourceDBName', models.CharField(blank=True, max_length=30, null=True)),
                ('sourceDBHost', models.CharField(blank=True, max_length=30, null=True)),
                ('sourceDBPort', models.IntegerField(blank=True, null=True)),
                ('sourceFilePath', models.CharField(blank=True, max_length=200, null=True)),
                ('jobid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='api.ReplicationJobs')),
            ],
        ),
        migrations.AddField(
            model_name='jobstatistics',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobstatssources', to='api.ReplicationJobs'),
        ),
        migrations.AddField(
            model_name='fieldmap',
            name='fmeColumnType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='FMEDataTypes', to='api.FMEDataTypes'),
        ),
        migrations.AddField(
            model_name='fieldmap',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ReplicationJobs', to='api.ReplicationJobs'),
        ),
        migrations.AddField(
            model_name='fieldmap',
            name='whoCreated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fieldmap',
            name='whoUpdated',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_updated', to=settings.AUTH_USER_MODEL),
        ),
    ]
