# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-15 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicationjobs',
            name='jobLabel',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
