# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-05 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180816_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sources',
            name='sourceTable',
            field=models.CharField(help_text='Source Table Name', max_length=161),
        ),
    ]
