# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_transformers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformers',
            name='ts6_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts6_value',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
