# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-14 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20180914_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transformers',
            name='ts1_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts1_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts2_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts2_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts3_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts3_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts4_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts4_value',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts5_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='ts5_value',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
