# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-24 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180917_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='sources',
            name='sourceProjection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
