# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-16 23:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181016_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldmap',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ReplicationJobs', to='api.ReplicationJobs'),
        ),
        migrations.AlterField(
            model_name='transformers',
            name='jobid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trans_jobs', to='api.ReplicationJobs'),
        ),
    ]
