# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-11-09 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20181016_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replicationjobs',
            name='jobLabel',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
